// <auto-generated />
using System;
using AuthzPlane.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthzPlane.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuthzPlaneDbContext))]
    partial class AuthzPlaneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthzPlane.Domain.Authorization.RelationTuple", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Condition")
                        .HasColumnType("jsonb")
                        .HasColumnName("condition");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalWriteId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_write_id");

                    b.Property<string>("ObjectRef")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_ref");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("relation");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserRef")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_ref");

                    b.HasKey("Id")
                        .HasName("pk_relation_tuples");

                    b.HasIndex("TenantId", "UserRef")
                        .HasDatabaseName("ix_tuples_tenant_user");

                    b.HasIndex("TenantId", "ObjectRef", "Relation")
                        .HasDatabaseName("ix_tuples_tenant_object");

                    b.HasIndex("TenantId", "UserRef", "Relation", "ObjectRef")
                        .IsUnique()
                        .HasDatabaseName("ux_tuples_triple");

                    b.ToTable("relation_tuples", (string)null);
                });

            modelBuilder.Entity("AuthzPlane.Domain.Reconciliation.DriftFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("actual_value");

                    b.Property<string>("DesiredValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("desired_value");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("FieldPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("field_path");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResourceKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("resource_kind");

                    b.Property<string>("ResourceRef")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("resource_ref");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("severity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_drift_findings");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_drift_findings_run_id");

                    b.HasIndex("TenantId", "DetectedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_drift_open")
                        .HasFilter("resolved_at IS NULL");

                    b.ToTable("drift_findings", (string)null);
                });

            modelBuilder.Entity("AuthzPlane.Domain.Reconciliation.ReconcileChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("change_key");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("operation");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("ResourceKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("resource_kind");

                    b.Property<string>("ResourceRef")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("resource_ref");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_reconcile_changes");

                    b.HasIndex("ChangeKey")
                        .HasDatabaseName("ix_changes_change_key");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_reconcile_changes_run_id");

                    b.ToTable("reconcile_changes", (string)null);
                });

            modelBuilder.Entity("AuthzPlane.Domain.Reconciliation.ReconcileRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint")
                        .HasColumnName("generation");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<string>("SnapshotKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("snapshot_key");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trigger");

                    b.HasKey("Id")
                        .HasName("pk_reconcile_runs");

                    b.HasIndex("TenantId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_runs_tenant_started");

                    b.ToTable("reconcile_runs", (string)null);
                });

            modelBuilder.Entity("AuthzPlane.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint")
                        .HasColumnName("generation");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("AuthzPlane.Domain.Tenants.TenantSpec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("created_by");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint")
                        .HasColumnName("generation");

                    b.Property<string>("SpecHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("spec_hash");

                    b.Property<string>("SpecJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("spec_json");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_specs");

                    b.HasIndex("TenantId", "Generation")
                        .IsUnique()
                        .HasDatabaseName("ux_spec_generation");

                    b.ToTable("tenant_specs", (string)null);
                });

            modelBuilder.Entity("AuthzPlane.Domain.Tenants.TenantStatus", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ActualStateHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actual_state_hash");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastReconciledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reconciled_at");

                    b.Property<DateTimeOffset>("LastTransitionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_transition_at");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<long>("ObservedGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("observed_generation");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phase");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("TenantId")
                        .HasName("pk_tenant_status");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_status_next_attempt");

                    b.ToTable("tenant_status", (string)null);
                });

            modelBuilder.Entity("AuthzPlane.Domain.Authorization.RelationTuple", b =>
                {
                    b.HasOne("AuthzPlane.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relation_tuples_tenants_tenant_id");
                });

            modelBuilder.Entity("AuthzPlane.Domain.Reconciliation.DriftFinding", b =>
                {
                    b.HasOne("AuthzPlane.Domain.Reconciliation.ReconcileRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_drift_findings_reconcile_runs_run_id");
                });

            modelBuilder.Entity("AuthzPlane.Domain.Reconciliation.ReconcileChange", b =>
                {
                    b.HasOne("AuthzPlane.Domain.Reconciliation.ReconcileRun", null)
                        .WithMany("Changes")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reconcile_changes_reconcile_runs_run_id");
                });

            modelBuilder.Entity("AuthzPlane.Domain.Tenants.TenantSpec", b =>
                {
                    b.HasOne("AuthzPlane.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_specs_tenants_tenant_id");
                });

            modelBuilder.Entity("AuthzPlane.Domain.Tenants.TenantStatus", b =>
                {
                    b.HasOne("AuthzPlane.Domain.Tenants.Tenant", null)
                        .WithOne()
                        .HasForeignKey("AuthzPlane.Domain.Tenants.TenantStatus", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_status_tenants_tenant_id");
                });

            modelBuilder.Entity("AuthzPlane.Domain.Reconciliation.ReconcileRun", b =>
                {
                    b.Navigation("Changes");
                });
#pragma warning restore 612, 618
        }
    }
}
